# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3d02817b7cdc09362b90c125e6aea215e5efd3d3149fb260bba786f6646006cb2b0c352a505d8079c9965335f6241d62277e2afb99ca52da5ea18c8f857a12

test:
  secret_key_base: e2889c037a4523358192bb33e7626c97949240997db284fb8a07fa818ac445d3fece6e7d60804d9d55a207fdb1b259f88cd9694e3370c9633e5b5e7e48bdb545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
